### ISSUE TITLE
Need to run compile manually first.

### ISSUE THREAD

**Issue by Cwright017** [electron/electron-compile#126]
If I install the package as per the documentation, and then run `electron-packager-compile .` It packages but then when running the app I get an error saying it tried to look for main but it was not precompiled. 

It seems first running `electron-compile` and generating a .cache and then running packager seems to fix this. After that I can then delete the .cache and everything seems ok with packager working fine.

**Comment by buz-zard** [comment]
I'm having similliar issue, though `electron-packager-compile .` doesn't build anything, I have to `electron-compile .` and `electron-packager .` to get a working build.

[Code example](https://github.com/buz-zard/random/tree/master/electron-compile-1)

**Comment by malept** [comment]
`electron-packager-compile` has been removed from this project due to its unreliability _(see: most of the issues marked electron-packager in this issue tracker)_. It's now recommended to use the [Electron Forge](https://github.com/electron-userland/electron-forge) project, because it uses both electron-compile and Electron Packager (among other community projects) to create distributable Electron apps.
