### ISSUE TITLE
"electron-packager-compile --sign-osx" fails

### ISSUE THREAD

**Issue by aendrew** [electron/electron-compile#128]
If I run:

`electron-packager-compile . --out=dist --osx-sign --icon ./Apps-Console.icns --app-version=$npm_package_version --version=1.3.2 --asar --prune --overwrite --platform=darwin --arch=x64`

...and then:

`codesign --verify -vvvv dist/MyApp-darwin-x64/MyApp.app`

I get `file missing` warnings for the entirety of `node_modules`.

If I do the exact same with `electron-packager`, I get:

```
dist/MyApp-darwin-x64/Vocab.app: valid on disk
dist/MyApp-darwin-x64/Vocab.app: satisfies its Designated Requirement
```

This leads me to believe `electron-packager-compile` is not signing things properly.

**Comment by malept** [comment]
`electron-packager-compile` has been removed from this project due to its unreliability _(see: most of the issues marked electron-packager in this issue tracker)_. It's now recommended to use the [Electron Forge](https://github.com/electron-userland/electron-forge) project, because it uses both electron-compile and Electron Packager (among other community projects) to create distributable Electron apps.
