### ISSUE TITLE
Certain folders cause packaging to fail

### ISSUE THREAD

**Issue by reverentgeek** [electron/electron-compile#93]
Similar to the `app` folder issue in #61, it appears that if the project root folder contains a folder named `tasks`, it also breaks the packaging process. At least it does on Windows. I haven't tested it on OS/X yet. If I move the `tasks` folder under `src`, the packaged app works. If the folder is in the project root, the packaged app gives the same error, "Asked for ...main.js but it was not precompiled!"

Also, whenever this happens on Windows, there are two Electron processes that are left running after closing the error message. I have to kill these before I can try packaging again.

**Comment by malept** [comment]
`electron-packager-compile` has been removed from this project due to its unreliability _(see: most of the issues marked electron-packager in this issue tracker)_. It's now recommended to use the [Electron Forge](https://github.com/electron-userland/electron-forge) project, because it uses both electron-compile and Electron Packager (among other community projects) to create distributable Electron apps.

If this bug still occurs when using Electron Forge, please let us know.
